name: Sending silent push notifications

on: 
  workflow_dispatch:
  schedule:
      - cron: "*/6 * * * *"
jobs:
  Auth_to_Firebase:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: PrintToken
      run: |
        echo ${{ steps.auth.outputs.access_token }}
    - uses: 'fjogeleit/http-request-action@v1'
      id: 'myRequest'
      name: MakeRequest
      with:
        url: "https://fcm.googleapis.com/v1/projects/zenthoughts-c2424/messages:send"
        method: "POST"
        customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer ${{ steps.auth.outputs.access_token }}"}'
        data: '{"message": {"topic": "zennotification", "notification": {}, "apns": {"payload": {"aps": {"priority": "high","content_available": true}}}}}'
    - name: Show Response
      run: |
        echo ${{ steps.myRequest.outputs.response }}
        echo ${{ fromJson(steps.myRequest.outputs.response).field_you_want_to_access }}
#work       data: '{"message": {"topic": "zennotification", "notification": {"title": "Some title from GitHub", "body": "Some body from GitHub"}}}'
#       data: '{"message": {"topic": "zennotification", "notification": {"title": "Some title", "body": "Some body"}, "apns": {"payload": {"aps": {"priority": "high", "content_available": true}}}}}'
# jobs:
#   SendNotification:
#     runs-on: ubuntu-latest                                
#     steps:
#       - name: Make Request
#         id: myRequest
#         uses: fjogeleit/http-request-action@v1
#         with:
#           url: "https://fcm.googleapis.com/fcm/send"
#           method: "POST"
#           customHeaders: '{"Content-Type": "application/json", "Authorization": "key=AAAAyWB4oao:APA91bHrECRRT9T6MdX8tj1Xa24hEwoA0SAwq0_pJUTHVbItEr-JcjB8urfHYKfO9gcYCKFAljgjn1AeYU8QUNt4UkiPa79ax48eZW00HtNUFTe-GBTQ7RN4FZJHNHB_cb6pHzN2e84-"}'
#           data: '{"to": "/topics/zennotification", "priority": "high", "content_available": true}'
          
#       - name: Show Response
#         run: |
#           echo ${{ steps.myRequest.outputs.response }}
#           echo ${{ fromJson(steps.myRequest.outputs.response).field_you_want_to_access }}
