name: Sending silent push notifications

on: 
  workflow_dispatch:
  schedule:
      - cron: "*/6 * * * *"
jobs:
  SendNotification:
    runs-on: ubuntu-latest                                
    steps:
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://fcm.googleapis.com/fcm/send"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json", "Authorization": "key=AAAAyWB4oao:APA91bHrECRRT9T6MdX8tj1Xa24hEwoA0SAwq0_pJUTHVbItEr-JcjB8urfHYKfO9gcYCKFAljgjn1AeYU8QUNt4UkiPa79ax48eZW00HtNUFTe-GBTQ7RN4FZJHNHB_cb6pHzN2e84-"}'
          data: '{"to": "/topics/zennotification", "priority": "high", "content_available": true}'
          
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
          echo ${{ fromJson(steps.myRequest.outputs.response).field_you_want_to_access }}
